author:
  name: Jackie Tao
menu:
  main:
    - identifier: posts
      name: 文章
      url: /posts/
      weight: 1
      params:
        icon: fa-solid fa-archive
    - identifier: tutorials
      name: 教程
      url: /tutorials/
      weight: 2
    - identifier: news
      name: 新闻
      url: /news/
      weight: 3
    - identifier: work
      name: 工作
      url: /work/
      weight: 4